### ISSUE TITLE
Atomic NAND can't be emulated for byte/half-words with this proposal

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-zabha#13]
LR/SC pairs can be used to emulate atomic operations, and so can be used to emulate atomic NAND from C++-11 which is currently missing from RISC-V atomics, see https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html

By having byte/half-word atomics but not LR/SC then atomic NAND cannot be emulated on those data types.

Additionally the CHERI specification proposes addition of LR/SC on byte and half words, see https://github.com/CTSRD-CHERI/cheri-specification/releases

Given the trivial nature of including them in the specification, and the improvement in regularity compared to the current A extension, I propose that these should be included too.

**Comment by jrtc27** [comment]
AMOCAS is much more disruptive microarchitecturally; I imagine there are those who would like to be able to use bye/halfword LR/SC instead of pulling in an AMOCAS implementation with its three operand and possible register pair nature (i.e. up to five register reads and two register writes). Given it should be essentially free microarchitecturally (the reservation logic can be used unchanged and the bit extraction+extension/insertion logic in the cache already exists for normal loads/stores, so it's just decode logic) and they are more flexible than the AMOop (non-CAS) instructions I don't see a good reason not to include them.

**Comment by ved-rivos** [comment]
The cost of extending `LR`/`SC` may be relatively low but the utility was also considered to be low as `amocas` provides the flexibility of carrying out equivalent AMO. Register pairs are required only for `amocas.q` or `amocas.d` in RV32. Register pairs are not required to perform byte/halfword `amocas`.  Extensions to `LR`/`SC` may be pursued separately if a more compelling justification if found.

**Comment by jrtc27** [comment]
> Register pairs are required only for amocas.q or amocas.d in RV32. Register pairs are not required to perform byte/halfword amocas.

But Zacas is all one extension; you can't just have the non-pair AMOCAS instructions. I mean, you could with PMAs I guess, but just as you would be deemed a bad person for only supporting a subset of normal AMOs in main memory so too would you for doing that for AMOCAS.

Plus, non-pair AMOCAS is _still_ microarchitecturally more disruptive than byte/halfword LR/SC, which are completely non-disruptive.

**Comment by ved-rivos** [comment]
Profile compliant implementations will implement all `amocas` and on such implementations NAND can be realized using `amocas.b/h`. Custom non-profile implementations that want to exclude `amocas.d/q` do have the choice of implementing a subset or `amocas` or a custom `LR`/`SC` extension.

**Comment by ved-rivos** [comment]
This question was discussed by ARC on 10/17 and the following [resolution](https://lists.riscv.org/g/tech-unprivileged/message/581) was provided. 

> We recommended these remain different extensions, as they are of different value to different ecosystems.  We also note that the word-sized variants are also split into two extensions (Zaamo and Zalrsc) to meet the needs of different ecosystems.  We recommend the parties who need "Zabhlrsc" pursue it as a separate fast-track extension.
