### ISSUE TITLE
Sign extension

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-zabha#14]
Presumably these instructions all sign-extend the result written into `rd`, just like the AMO.W versions currently do in RV64.  This might be OK, but I want to make sure it's the best decision.

As a reminder, AMO.W always sign-extends because 32b values are always sign-extended when held in RV64 x-registers, regardless of whether the values are logically signed or unsigned.  The same isn't true of 8b and 16b values, which are zero-extended if unsigned or sign-extended if signed.

For HW simplicity, we probably should either sign-extend all of AMO.B/AMO.H or zero-extend all of them.  The question is, is sign-extension or zero-extension the more common case?  Do we have any data on that?

**Comment by ved-rivos** [comment]
I missed adding that the proposal was to zero extended and for signed operands require the compiler to emit an additional  `sext`. I am not sure there is a good way to  find the common case. I will try to do some research on this question.

**Comment by aswaterman** [comment]
You could try building the compiler both ways then building the Linux kernel both ways.

It occurred to me that it's better to favor sign-extension over zero-extension when comparisons are involved, though.  If you unconditionally sign-extend, then both unsigned branches (BLTU/BGEU) and signed branches (BLT/BGE) work property without any extensions.  If you unconditionally zero-extend, then only unsigned branches work properly.

So, if you don't have time to run the experiment, I'd suggest switching to unconditional sign-extension.  If you do have time to run the experiment, I'm curious to hear the results.

**Comment by ved-rivos** [comment]
That's a good point about branches being agnostic. I will switch the proposal to the unconditional sign-extension. 
I will do the experiment, out of curiosity. On the linux kernel, It may be just be possible to grep for amo invocations and the data type used with them as a first experiment. For [example](https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L168).

**Comment by aswaterman** [comment]
Ack.  I think it depends not just on datatype but also on how the result is used so the grepping experiment might lend the wrong impression.

**Comment by ved-rivos** [comment]
Updated in PR #15
