### ISSUE TITLE
Possible clarification?: `amocas.[bh]*` requirements

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-zabha#18]
> `Zabha` extends `A` and `Zacas` standard extensions by adding byte (`width=0`) and halfword (`width=1`) support in width field for atomic memory operation instructions.

Considering this sentence, it's natural to assume that `AMOCAS.[BH]` instructions require *both* `Zabha` and `Zacas`.  Whether or not my understandings are correct, I hope this point to be further clarified.

Note that extension dependency / implication (current implication: `Zabha` → `A`) do not need to be changed/added even if my understandings are correct.

**Comment by ved-rivos** [comment]
Zacas specifies that it depends on A. Implementing `amocas` requires implementing A. Zabha extends A and Zacas. Zabha does not depend on or imply Zacas.

**Comment by a4lg** [comment]
I see. What I request is further clarification like "AMOCAS.B and AMOCAS.H instructions are implemented if the Zacas extension is also implemented."

**Comment by ved-rivos** [comment]
It was implied by Zabha extending Zacas. Zabha does not introduce the `amocas` instruction. It only extends the `amocas` instruction introduced by Zacas by adding the byte and halfword width encodings.

**Comment by aswaterman** [comment]
"Extends" isn't a verb we normally use in describing RISC-V extensions, and so I think @a4lg's concern is valid.  I think it would help to explicitly say something like, "Zabha provides AMO[ADD|AND|OR|XOR|SWAP|MIN[U]|MAX[U]].[B|H].  If Zacas is additionally implemented, Zabha additionally provides AMOCAS.[B|H]."

**Comment by ved-rivos** [comment]
Made the update in PR #19

**Comment by aswaterman** [comment]
Approved & merged, so I think we can close this issue.  @a4lg let us know if you think this change was insufficient.

**Comment by a4lg** [comment]
@aswaterman
I think this is sufficient.

@ved-rivos
I really appreciate your clarification work and thanks for discussing me actively.
