### ISSUE TITLE
Dependency to Zaamo

### ISSUE THREAD

**Issue by henry-hsieh** [riscv/riscv-zabha#23]
The latest commit changed the Zabha dependency from A to Zaamo. I knew everyone used to using Zaamo as referring atomic operations in A extension. However, Zaamo is not a ratified extension or a developing fast track extension. I think that the definition of Zaamo should be also defined in this spec, or be proposed as a new fast track extension like Zmmul.

**Comment by ved-rivos** [comment]
This is a result of partially fixing the issue raised in https://github.com/riscv/riscv-zabha/issues/18
As agreed in the issue #18, I will remove the statement "Zabha extends A and Zacas [2] standard extensions by...".

**Comment by ved-rivos** [comment]
@aswaterman do you agree that its best to remove the first sentence as the second sentence "Zabha provides..." is complete by itself?

**Comment by henry-hsieh** [comment]
Does the Zabha depends on A or Zaamo extension? If it's true, a new sentence "Zabha depends on ..." may need to be added IMO.

**Comment by ved-rivos** [comment]
For dependency - it depends on A. Thats noted in the specification.

**Comment by henry-hsieh** [comment]
I saw it. Never mind.

**Comment by ved-rivos** [comment]
updated in PR #25
