### ISSUE TITLE
Are there byte/halfword LR/SC instructions?

### ISSUE THREAD

**Issue by wangpc-pp** [riscv/riscv-zabha#36]
It seems we don't have byte/halfword LR/SC instructions. There are equivalent instructions in ARM.
Any plan to add these? Or did I miss somthing?

**Comment by ved-rivos** [comment]
The Zabha extension did not add byte/halfword LR/SC instructions due to low utility as noted [here](https://github.com/riscv/riscv-zabha/blob/1f1e497edec3229aeb35e78c2078b24fb163fcda/src/zabha.adoc?plain=1#L38). At the moment there are no plans to add them.
